config/routes.rb
Rails.application.routes.draw do
  resources :characterisations
  resources :genres
  root "movies#index"

  resources :movies

  get "movies/filter/:filter" => "movies#index", as: :filtered_movies

  resources :movies do
    resources :reviews
    resources :favourites, only: [:create, :destroy]
  end

  resource :session, only: [:new, :create, :destroy]
  get "signin" => "sessions#new"

  resources :users
  get "signup" => "users#new"
end

app/models/genre.rb
class Genre < ApplicationRecord
  before_save :set_slug

  has_many :characterisations, dependent: :destroy
  has_many :movies, through: :characterisations

  validates :name, presence: true, uniqueness: true

  def to_param
    slug
  end

  private

  def set_slug
    self.slug = name.parameterize
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :require_signin, except: [:index, :show]
  before_action :require_admin, except: [:index, :show]
  before_action :set_genre, except: [:index, :new, :create]

  def index
    @genres = Genre.all
  end

  def show
    @movies = @genre.movies
  end

  def edit
  end

  def update
    if @genre.update(genre_params)
      redirect_to @genre, notice: "Genre successfully updated!"
    else
      render :edit
    end
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to @genre, notice: "Genre successfully created!"
    else
      render :new
    end
  end

  def destroy
    @genre.destroy
    redirect_to genres_url, alert: "Genre successfully deleted!"
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

  def set_genre
    @genre = Genre.find_by!(slug: params[:id])
  end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.html.erb
<%= form_with(model: genre, local: true) do |f| %>
  <%= render "shared/errors", object: genre %>

  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true %>

  <% if genre.new_record? %>
    <%= f.submit "Create Genre" %>
  <% else %>
    <%= f.submit "Update Genre" %>
  <% end %>
<% end %>

app/views/genres/edit.html.erb
<h1>Edit Genre: <%= @genre.name %></h1>
<%= render "form", genre: @genre %>

app/views/genres/index.html.erb
<h1>Genres</h1>
<section>
  <ul class="users">
    <% @genres.each do |genre| %>
      <li>
        <%= link_to genre.name, genre %>
      </li>
    <% end %>
  </ul>
</section>

<% if current_user_admin? %>
  <section class="admin">
    <%= link_to "Add New Genre", new_genre_path(@movie), class: "button" %>
  </section>
<% end %>

app/views/genres/new.html.erb
<h1>Create Genre</h1>
<%= render "form", genre: @genre %>

app/views/genres/show.html.erb
<section class="user">
  <h1><%= @genre.name %> Details</h1>
  <!-- <h3>Created</h3> -->
  <p>
    Created <%= @genre.created_at.strftime("%B %Y") %>
  </p>
  <div class="actions">
    <% if current_user_admin? %>
      <%= link_to "Edit Genre", edit_genre_path(@genre),
                  class: "button edit" %>
      <%= link_to "Delete Genre", @genre, class: "button delete",
                  method: :delete,
                  data: { confirm: 'Permanently delete this genre?' } %>
    <% end %>
  </div>
  <% if @movies.present? %>
    <h3><%= @genre.name %> Movies</h3>
    <% @movies.each do |movie| %>
      <ul>
        <li>
          <%= link_to movie.title, movie %>
        </li>
      </ul>
    <% end %>
  <% end %>
</section>